server:
  port: 9875
spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    url: jdbc:p6spy:mysql://172.25.252.193:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: sasa
  cloud:
    inetutils:
      preferred-networks:
      - 172.25.252.193
    
logging:
  config: classpath:logback.xml
    
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      
xxl:
  job:
    admin:
      addresses: http://172.25.252.193:8088/xxl-job-admin
    executor:
      appname: golden-job-center
      ip: 172.25.252.193
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 10
    accessToken:       
      
      